import {useState} from 'react';
import {Check,Minus,RotateCcw,SlidersHorizontal} from 'lucide-react';
import {Sheet} from '../components/Sheet';
import {formatDate,ruleOn,targetLabel,meetsTarget,type Habit,type Entry} from '../domain/model';
export function EntrySheet({habit,date,entry,onClose,onSave,onEdit}:{habit:Habit;date:string;entry?:Entry;onClose:()=>void;onSave:(status:Entry['status'],value:number|null)=>void;onEdit:()=>void}) {
 const rule=ruleOn(habit,date)!;const [value,setValue]=useState(entry?.value?.toString()||'');const [error,setError]=useState('');
 function save(){const number=Number(value.replace(',','.'));if(!value.trim()||!Number.isFinite(number)||number<0||number>1000000){setError('Enter a number from 0 to 1,000,000.');return;}onSave(meetsTarget(rule,number)?'met':'not-met',number);}
 return <Sheet title={habit.name} subtitle={formatDate(date,{weekday:'long',month:'long',day:'numeric',year:'numeric'})} onClose={onClose}><div className={`entry-intro ${habit.color}`}><span className="color-dot"/>{rule.kind==='number'?targetLabel(rule):'How did it go?'}</div>{rule.kind==='number'?<form onSubmit={e=>{e.preventDefault();save();}}><label className="field"><span>{rule.unit||'Value'}</span><input autoFocus inputMode="decimal" placeholder="0" value={value} onChange={e=>{setValue(e.target.value);setError('');}} aria-invalid={!!error} aria-describedby={error?'number-error':undefined}/>{error&&<span id="number-error" className="field-error">{error}</span>}</label>{habit.icon==='sleep'&&<p className="help-text">Log last night’s sleep on the day you woke up.</p>}<div className="sheet-actions"><button className="primary-button" type="submit">Save entry</button></div></form>:<div className="entry-options"><button className="primary-button" onClick={()=>onSave('met',null)}><Check size={20}/>Met</button><button className="secondary-button" onClick={()=>onSave('not-met',null)}><Minus size={20}/>Not met</button></div>}<div className="entry-secondary"><button onClick={()=>onSave('unlogged',null)}><RotateCcw size={17}/>Clear entry</button><button onClick={onEdit}><SlidersHorizontal size={17}/>Habit settings</button></div></Sheet>;
}
