import {useState} from 'react';
import {ChevronLeft,ChevronRight,ArrowUpRight} from 'lucide-react';
import {HistoryGrid} from '../components/HistoryGrid';
import {addDays,dayState,formatDate,streaks,review,weekStart,type Data,type Habit} from '../domain/model';
export function History({data,today,onEntry,onEdit,onAdd}:{data:Data;today:string;onEntry:(habit:Habit,date:string)=>void;onEdit:(habit:Habit)=>void;onAdd:()=>void}) {
 const [end,setEnd]=useState(today);const [showArchived,setShowArchived]=useState(false);
 const days=Array.from({length:7},(_,i)=>addDays(end,i-6));
 const habits=data.habits.filter(h=>showArchived||!h.archivedOn);
 const previousWeek=addDays(weekStart(today),-7);const summary=review(data.habits,data.entries,previousWeek,addDays(previousWeek,6),today);
 const rows=habits.map(h=>({id:h.id,name:h.name,color:h.color,current:streaks(h,data.entries,today).current,states:days.map(d=>dayState(h,d,data.entries,today))}));
 return <><div className="history-toolbar"><div><p className="eyebrow">SEVEN DAYS AT A TIME</p><h2>{formatDate(days[0],{month:'short',day:'numeric'})} – {formatDate(end,{month:'short',day:'numeric',year:'numeric'})}</h2></div><div className="history-controls"><button className="icon-button" aria-label="Previous week" onClick={()=>setEnd(addDays(end,-7))}><ChevronLeft size={20}/></button><button className="week-today" onClick={()=>setEnd(today)}>Today</button><button className="icon-button" aria-label="Next week" disabled={end>=today} onClick={()=>setEnd(addDays(end,7)>today?today:addDays(end,7))}><ChevronRight size={20}/></button></div></div>{habits.length?<HistoryGrid rows={rows} days={days} today={today} onCell={(id,date)=>{const habit=data.habits.find(h=>h.id===id);if(habit)onEntry(habit,date);}}/>:<div className="empty-state"><h2>Your story starts with one habit.</h2><p>A small check-in today becomes a bigger picture over time.</p><button className="primary-button" onClick={onAdd}>Add your first habit</button></div>}{data.habits.some(h=>h.archivedOn)&&<label className="checkbox-label"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Include archived habits</label>}<section className="weekly-review"><div className="review-heading"><div><p className="eyebrow">A MOMENT TO LOOK BACK</p><h2>Last week, at a glance.</h2></div><span>{formatDate(previousWeek,{month:'short',day:'numeric'})} – {formatDate(addDays(previousWeek,6),{month:'short',day:'numeric'})}</span></div>{summary.total?<><div className="review-totals"><div><strong>{summary.met}<span> / {summary.total}</span></strong><p>scheduled goals met</p></div><div><strong>{summary.missed}</strong><p>not met</p></div><div><strong>{summary.unlogged}</strong><p>not logged</p></div></div><div className="review-rows">{summary.rows.map(row=><div key={row.habit.id} className={`review-row ${row.habit.color}`}><div><span className="color-dot"/><strong>{row.habit.name}</strong><small>{row.current} current · {row.best} best streak</small></div><div className="review-bar"><i style={{width:`${Math.round(row.met/row.total*100)}%`}}/></div><span>{Math.round(row.met/row.total*100)}%</span><button className="icon-button" aria-label={`Adjust ${row.habit.name}`} onClick={()=>onEdit(row.habit)}><ArrowUpRight size={18}/></button></div>)}</div></>:<p className="help-text">Your first weekly review will appear here after you’ve started tracking. There’s no need to fill in the past.</p>}</section></>;
}
