import {
  Sprout,
  Check,
  CalendarDays,
  Clock,
  Target,
  Trophy,
  Repeat,
  ListChecks,
  Dumbbell,
  Footprints,
  Bike,
  Activity,
  HeartPulse,
  PersonStanding,
  Mountain,
  Waves,
  Brain,
  BookOpen,
  NotebookPen,
  GraduationCap,
  Languages,
  Lightbulb,
  Puzzle,
  Focus,
  Utensils,
  Leaf,
  Droplets,
  Apple,
  Carrot,
  Salad,
  Coffee,
  CookingPot,
  Moon,
  Sun,
  BedDouble,
  ShowerHead,
  Smile,
  Heart,
  Flower2,
  Hand,
  Music,
  Guitar,
  Palette,
  Camera,
  Code2,
  Briefcase,
  House,
  PiggyBank,
  type LucideIcon,
} from "lucide-react";
import type { HabitIconId } from "../domain/icons";

export const habitIconComponents: Record<HabitIconId, LucideIcon> = {
  habit: Sprout,
  check: Check,
  calendar: CalendarDays,
  clock: Clock,
  target: Target,
  trophy: Trophy,
  repeat: Repeat,
  list: ListChecks,
  workout: Dumbbell,
  walk: Footprints,
  bike: Bike,
  activity: Activity,
  pulse: HeartPulse,
  stretch: PersonStanding,
  mountain: Mountain,
  waves: Waves,
  brain: Brain,
  book: BookOpen,
  journal: NotebookPen,
  study: GraduationCap,
  language: Languages,
  idea: Lightbulb,
  puzzle: Puzzle,
  focus: Focus,
  food: Utensils,
  leaf: Leaf,
  water: Droplets,
  apple: Apple,
  carrot: Carrot,
  salad: Salad,
  coffee: Coffee,
  cooking: CookingPot,
  sleep: Moon,
  sun: Sun,
  bed: BedDouble,
  shower: ShowerHead,
  smile: Smile,
  heart: Heart,
  flower: Flower2,
  hand: Hand,
  music: Music,
  guitar: Guitar,
  art: Palette,
  camera: Camera,
  code: Code2,
  work: Briefcase,
  home: House,
  savings: PiggyBank,
};
export function HabitIcon({ habit }: { habit: { icon: HabitIconId } }) {
  const Icon = habitIconComponents[habit.icon] || Sprout;
  return <Icon size={22} strokeWidth={1.8} aria-hidden="true" />;
}
