import { Check, Plus, LayoutGrid, CalendarDays, Settings2, ArrowUpRight, Dumbbell, Utensils, Moon, Leaf } from 'lucide-react';

const habits = [
  {name: 'Workout', detail: 'Make a little time to move.', color: 'mint', icon: Dumbbell},
  {name: 'No fast food', detail: 'A little more intentional.', color: 'peach', icon: Utensils},
  {name: 'Sleep', detail: 'Goal: at least 9 hours', color: 'lavender', icon: Moon},
  {name: 'Healthy calories', detail: 'Your 2000-calorie goal', color: 'yellow', icon: Leaf},
];
export default function App() {
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/"><img src="/favicon.svg" alt=""/>habit-grid<span>®</span></a><div className="side-caption">A LITTLE, EVERY DAY</div><nav><button className="nav-item active"><LayoutGrid size={20}/>Today<span className="nav-count">4</span></button><button className="nav-item"><CalendarDays size={20}/>History</button><button className="nav-item"><Settings2 size={20}/>Settings</button></nav><div className="sidebar-bottom"><div className="tiny-grid">{Array.from({length:20},(_,i)=><i key={i} style={{opacity:(i%4+1)/4}}/>)}</div><p>Small steps.<br/>A bigger picture.</p><span>YOUR SPACE TO KEEP GOING</span></div></aside><main><div className="topline"><span>YOUR DAILY PRACTICE</span><span className="device-status">Saved on this device</span></div><header className="page-heading"><div><p className="eyebrow">THURSDAY, SEPTEMBER 24</p><h1>Today<span className="title-dot">.</span></h1><p className="subtitle">A fresh square. A little progress.</p></div><button className="add-button"><Plus size={20}/><span>Add habit</span></button></header><div className="today-layout"><section className="today-list"><div className="progress-section"><div><strong>0 <span>of 4 goals met</span></strong><span>ONE STEP AT A TIME</span></div><div className="progress-track">{habits.map(h=><i key={h.name}/>)}</div></div><div className="habit-list">{habits.map(({name,detail,color,icon:Icon})=><article className={`habit-row ${color}`} key={name}><div className="habit-icon"><Icon size={22}/></div><button className="habit-body"><strong>{name}</strong><span>{detail}</span><div className="mini-history">{Array.from({length:7},(_,i)=><i className={i===6?'current':''} key={i}/>)}</div></button><button className={`check-control ${name==='Sleep'?'numeric':''}`} aria-label={`Log ${name}`}>{name==='Sleep'?<>Log<br/>hours</>:<Check size={22}/>}</button></article>)}</div><div className="list-footer"><span>Make today a day you can see.</span><span>↳ ONE CHECK-IN AT A TIME</span></div></section><aside className="today-aside"><div className="rhythm-card"><div className="section-kicker">THE BIGGER PICTURE<ArrowUpRight size={18}/></div><h2>Find your<br/>everyday rhythm.</h2><div className="rhythm-grid">{Array.from({length:49},(_,i)=><i key={i} className={i>41?'outlined':`shade-${i%5}`}/>)}</div><p>Your small daily choices,<br/>all in one place.</p><button className="text-button">Explore your history <ArrowUpRight size={16}/></button></div><div className="quiet-note"><span>01 / A NOTE TO SELF</span><p>Consistency has room<br/>for being human.</p></div></aside></div><footer className="page-footer"><span>Little by little adds up.</span><span>habit-grid / YOUR OWN PACE</span></footer></main><nav className="mobile-nav"><button className="active"><LayoutGrid size={20}/>Today</button><button><CalendarDays size={20}/>History</button><button><Settings2 size={20}/>Settings</button></nav></div>;
}
